# Documentation for JIT policy: https://aka.ms/gim/docs/policy/jit

# metadata
id: id
name: JIT_Access
description: Policy for admin JIT for repos in this org

# filters
resource: repository

# primitive configuration
configuration:
  jitAccess:
    enabled: true
    maxHours: 8
    approvers:
      role:
      users:
    requestors:
      role:
      users:
        - 'jgbradley1'
        - 'americanthinker'
        - 'dorbaker'
        - 'richardjortega'
