trigger:
- main

# the `resources` specify the location and version of the 1ES Pipeline Template (PT).
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  # this pipeline extends an existing 1ES PT which injects various SDL and compliance tasks
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: OCTO1ES_HostedPool
      image: SMTOCTO1ESAgentWindowsVM
      os: windows
    sdl:
      skipComponentGovernanceDetection: false
      policheck:
        enabled: true
      sourceAnalysisPool:
        name: OCTO1ES_HostedPool
        image: SMTOCTO1ESAgentWindowsVM
        os: windows
    stages:
      - stage: Component_Governance
        jobs:
        - job: CG_Prep
          steps:
            # Component Governance (CG) does not support pyproject.toml yet.
            # For this reason, use toml-to-requirements to export dependencies into a requirements.txt file.
            # CG will auto-detect the requirements.txt file and use it to scan for dependencies.
            - script: |
                pip install toml-to-requirements
                toml-to-req --toml-file backend/pyproject.toml --poetry --optional-lists dev,test,backend,frontend
                # toml-to-req is not perfect. It will leave wildcard characters in the requirements.txt file which we remove
                sed -i 's/\*//g' requirements.txt
              displayName: 'Export python dependencies to requirements.txt for CG'
