trigger:
- main

# the `resources` specify the location and version of the 1ES Pipeline Template (PT).
resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  # this pipeline extends an existing 1ES PT which injects various SDL and compliance tasks
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: OCTO1ES_HostedPool
      image: SMTOCTO1ESAgentWindowsVM
      os: windows
    sdl:
      policheck:
        enabled: true
      sourceAnalysisPool:
        name: OCTO1ES_HostedPool
        image: SMTOCTO1ESAgentWindowsVM
        os: windows
