trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - script: |
      pip install toml-to-requirements
      toml-to-req --toml-file pyproject.toml --poetry --optional-lists dev,test,backend,frontend
      # toml-to-req is not perfect. It will leave wildcard characters in the requirements.txt file which we remove
      sed -i 's/\*//g' requirements.txt
    displayName: 'Export python dependencies to requirements.txt'
  - task: ComponentGovernanceComponentDetection@0
    displayName: 'Component Governance - Component Detection'
    inputs:
      scanType: 'Register'
      verbosity: 'Verbose'
      alertWarningLevel: 'High'
  # - task: PoliCheck@2
  #   displayName: 'Run PoliCheck'
  #   inputs:
  #     targetType: 'F'
  #     targetArgument: '$(Build.SourcesDirectory)'
  #     result: 'PoliCheck.xml'
  #     toolVersion: Latest
