exclude: "tests/data"
repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.7.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: requirements-txt-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
      - id: check-json
        exclude: "devcontainer.json"
      - id: pretty-format-json
        args:
          - "--autofix"
        exclude: 'tests/|devcontainer.json|^.*\.ipynb$'
      - id: end-of-file-fixer
        files: \.(py|sh|bash|conf|yaml|yml|toml|ini)$
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.6
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
