apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "graphrag.index.fullname" . }}
  labels:
    {{- include "graphrag.index.labels" . | nindent 4 }}
spec:
  {{- if not .Values.index.autoscaling.enabled }}
  replicas: {{ .Values.index.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "graphrag.index.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.index.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        date: "{{ now | unixEpoch }}"
        {{- include "graphrag.index.labels" . | nindent 8 }}
        {{- with .Values.index.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "graphrag.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.index.podSecurityContext | nindent 8 }}
      containers:
        - name: "index"
          securityContext:
            {{- toYaml .Values.index.securityContext | nindent 12 }}
          image: "{{ .Values.index.image.repository }}:{{ .Values.index.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.index.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "graphrag.fullname" . }}
          ports:
            - name: http
              containerPort: {{ .Values.index.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.index.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.index.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.index.resources | nindent 12 }}
          volumeMounts:
          {{- with .Values.index.volumeMounts }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.index.volumes }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.index.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.index.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.index.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
