apiVersion: v1
kind: Service
metadata:
  name: {{ include "graphrag.query.fullname" . }}
{{- if .Values.query.service.annotations }}
  annotations:
  {{- range $key, $value := .Values.query.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    {{- include "graphrag.query.labels" . | nindent 4 }}
spec:
  type: {{ .Values.query.service.type }}
  ports:
    - port: {{ .Values.query.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "graphrag.query.selectorLabels" . | nindent 4 }}
