# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# For more information about the base image visit:
# https://mcr.microsoft.com/en-us/artifact/mar/devcontainers/python/about
FROM mcr.microsoft.com/devcontainers/python:3.10-bookworm

ENV PIP_ROOT_USER_ACTION=ignore
ENV PIP_DISABLE_PIP_VERSION_CHECK=1
ENV SETUPTOOLS_USE_DISTUTILS=stdlib

COPY frontend /frontend
RUN cd frontend \
    && pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry install

WORKDIR /frontend
EXPOSE 8080
CMD ["streamlit", "run", "app.py", "--server.port", "8080"]
