# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

# NOTE: the location of this file is important, as it is referenced by the api/index.py script
# and depends on the relative path to this file when uvicorn is run

apiVersion: batch/v1
kind: Job
metadata:
  name: PLACEHOLDER
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 6
  template:
    metadata:
      labels:
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: PLACEHOLDER
      restartPolicy: OnFailure
      containers:
      - name: graphrag
        image: PLACEHOLDER
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "4"
            memory: "24Gi"
          limits:
            cpu: "8"
            memory: "32Gi"
        envFrom:
        - configMapRef:
            name: graphrag
        command: [PLACEHOLDER]
