name: Release
on:
  release:
    types: [published]
jobs:
  build-backend-and-release:
    runs-on: [ self-hosted, 1ES.Pool=smt-runners ]
    permissions:
      id-token: write
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: '${{ secrets.AZURE_CREDENTIALS }}'
      - name: Get the version tag
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Build and push docker image
        run: |
          TAG=${{ steps.get_version.outputs.VERSION }}
          az acr build --registry ${{ vars.CONTAINER_REGISTRY_SERVER }} --build-arg GRAPHRAG_VERSION=$TAG -f docker/Dockerfile-backend --image graphrag:$TAG .
